### ISSUE TITLE
Which ruby version is needed?

### ISSUE THREAD

**Issue by ursforrer** [planio-gmbh/html2odt#1]
If i run it, this error apperas:
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': /usr/local/rvm/gems/ruby-1.9.3-p551/gems/html2odt-0.3.3/lib/html2odt/document.rb:17: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
  def initialize(template: Html2Odt::ODT_TEMPLATE, html: nil)
                          ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/html2odt-0.3.3/lib/html2odt/document.rb:17: dynamic constant assignment
  def initialize(template: Html2Odt::ODT_TEMPLATE, html: nil)
                                                  ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/html2odt-0.3.3/lib/html2odt/document.rb:17: syntax error, unexpected tLABEL, expecting '='
  def initialize(template: Html2Odt::ODT_TEMPLATE, html: nil)
                                                        ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/html2odt-0.3.3/lib/html2odt/document.rb:423: syntax error, unexpected keyword_end, expecting $end
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/html2odt-0.3.3/lib/html2odt.rb:16:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/html2odt-0.3.3/bin/html2odt.rb:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/html2odt.rb:23:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/html2odt.rb:23:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

Is there any solution for that?

**Comment by jkraemer** [comment]
This problem should go away by upgrading to at least Ruby 2.0.
You should really upgrade to something more recent, like at least Ruby 2.2. 1.9.x does not receive any bug fixes or security related patches any more.
